-- | Reusable @hedgehog-classes@ 'Laws' for the rank-2 (higher-kinded) functor
-- classes in "Kindly.Rank2", whose objects are themselves type constructors and
-- whose morphisms are natural transformations.
--
-- 'bmapLaws' covers a 'BFunctor' @b@ — a 'CategoricalFunctor' whose domain is
-- the functor category @(->) '~>' (->)@, so @'bmap'@ lifts a natural
-- transformation @forall x. f x -> g x@. 'bmap2Laws' covers a 'BFunctor2' @b@,
-- whose morphisms are natural transformations between bifunctors,
-- @forall x x'. p x x' -> p x x'@.
--
-- Natural transformations cannot be generated by hedgehog, so — like the fixed
-- sample functions in "Kindly.Functor.Laws" — each bundle is checked at a
-- caller-chosen witness functor with two sample natural endo-transformations to
-- compose, comparing @b f@ values with 'Eq'.
module Kindly.Rank2.Laws
  ( bmapLaws,
    bmap2Laws,
  )
where

--------------------------------------------------------------------------------

import Hedgehog (Gen, Property, forAll, property, (===))
import Hedgehog.Classes (Laws (..))
import Kindly.Rank2 (BFunctor, BFunctor2, bmap, bmap2)
import Prelude

--------------------------------------------------------------------------------
-- BFunctor (domain @(->) ~> (->)@)

-- | Identity (@'bmap' 'id' = 'id'@) and composition
-- (@'bmap' (n1 . n2) = 'bmap' n1 . 'bmap' n2@) for a 'BFunctor' @b@, checked at a
-- witness functor @f@ (whose @b f@ is 'Eq' \/ 'Show') using two sample natural
-- endo-transformations @forall x. f x -> f x@.
bmapLaws ::
  forall b f.
  (BFunctor b, Eq (b f), Show (b f)) =>
  Gen (b f) ->
  (forall x. f x -> f x) ->
  (forall x. f x -> f x) ->
  Laws
bmapLaws genB n1 n2 =
  Laws
    "BFunctor"
    [ ("Identity", bmapIdentity genB),
      ("Composition", bmapComposition genB n1 n2)
    ]

bmapIdentity ::
  forall b f.
  (BFunctor b, Eq (b f), Show (b f)) =>
  Gen (b f) ->
  Property
bmapIdentity genB = property $ do
  bf <- forAll genB
  bmap (\fx -> fx) bf === bf

bmapComposition ::
  forall b f.
  (BFunctor b, Eq (b f), Show (b f)) =>
  Gen (b f) ->
  (forall x. f x -> f x) ->
  (forall x. f x -> f x) ->
  Property
bmapComposition genB n1 n2 = property $ do
  bf <- forAll genB
  bmap (\fx -> n1 (n2 fx)) bf === bmap n1 (bmap n2 bf)

--------------------------------------------------------------------------------
-- BFunctor2 (domain @(->) ~> ((->) ~> (->))@)

-- | Identity and composition for a 'BFunctor2' @b@, checked at a witness
-- bifunctor @p@ (whose @b p@ is 'Eq' \/ 'Show') using two sample natural
-- endo-transformations @forall x x'. p x x' -> p x x'@.
bmap2Laws ::
  forall b p.
  (BFunctor2 b, Eq (b p), Show (b p)) =>
  Gen (b p) ->
  (forall x x'. p x x' -> p x x') ->
  (forall x x'. p x x' -> p x x') ->
  Laws
bmap2Laws genB n1 n2 =
  Laws
    "BFunctor2"
    [ ("Identity", bmap2Identity genB),
      ("Composition", bmap2Composition genB n1 n2)
    ]

bmap2Identity ::
  forall b p.
  (BFunctor2 b, Eq (b p), Show (b p)) =>
  Gen (b p) ->
  Property
bmap2Identity genB = property $ do
  bp <- forAll genB
  bmap2 (\px -> px) bp === bp

bmap2Composition ::
  forall b p.
  (BFunctor2 b, Eq (b p), Show (b p)) =>
  Gen (b p) ->
  (forall x x'. p x x' -> p x x') ->
  (forall x x'. p x x' -> p x x') ->
  Property
bmap2Composition genB n1 n2 = property $ do
  bp <- forAll genB
  bmap2 (\px -> n1 (n2 px)) bp === bmap2 n1 (bmap2 n2 bp)
