name: hlint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up HLint
        uses: haskell-actions/hlint-setup@v2
        with:
          version: "3.10"

      - name: Run HLint
        run: hlint src/ laws/ test/
